local Conductor = require("src.core.conductor")
return function(t)
  t.test("conductor step timing at 120bpm", function()
    local c = Conductor.new(120, 4)
    t.near(c:secondsPerStep(), 0.125)
    t.eq(c:stepAt(0), 0)
    t.eq(c:stepAt(0.124), 0)
    t.eq(c:stepAt(0.125), 1)
    t.near(c:beat(1.0), 2)
  end)
  t.test("advance reports each crossed step once", function()
    local c = Conductor.new(120, 4)
    local a, b = c:advance(0)
    t.eq(a, 0); t.eq(b, 0)
    t.eq(c:advance(0.05), nil)
    a, b = c:advance(0.3)
    t.eq(a, 1); t.eq(b, 2)
  end)
  t.test("advance caps catch-up after a stall", function()
    local c = Conductor.new(120, 4)
    c:advance(0)
    local a, b = c:advance(10)
    t.eq(b, 80)
    t.eq(b - a + 1, Conductor.MAX_CATCHUP)
  end)
  t.test("offset shifts the grid", function()
    local c = Conductor.new(120, 4, 0.5)
    t.eq(c:stepAt(0.4), -1)
    t.eq(c:stepAt(0.5), 0)
    c.userOffset = 0.1
    t.eq(c:stepAt(0.55), -1)
  end)
  t.test("beat phase is 0..1", function()
    local c = Conductor.new(60, 4)
    t.near(c:beatPhase(2.25), 0.25)
  end)
end
