local Stats = require("src.game.stats")
local Characters = require("src.data.characters")
return function(t)
  t.test("base stats with no bonuses", function()
    local s = Stats.compute(nil, {}, {})
    t.eq(s.maxHp, 100); t.near(s.moveSpeed, 150)
  end)
  t.test("bonuses stack from character, meta and passives", function()
    local s = Stats.compute(Characters.shredder, { might = 2, swiftness = 1 }, { protein_shake = 1, running_shoes = 2 })
    t.near(s.might, 1 + 0.15 + 0.10 + 0.10)
    t.near(s.moveSpeed, 150 * (1 + 0.04 + 0.16))
    t.eq(s.maxHp, 90)
  end)
end
