local Pattern = require("src.core.pattern")
return function(t)
  t.test("pattern parses and ignores separators", function()
    local p = Pattern.parse("X.x. | o...")
    t.eq(#p, 8)
    t.eq(p[1], 1); t.eq(p[3], 3); t.eq(p[5], 5); t.eq(p[2], 0)
  end)
  t.test("pattern rejects bad characters", function()
    t.truthy(not pcall(Pattern.parse, "X.?."))
    t.truthy(not pcall(Pattern.parse, "  | "))
  end)
  t.test("firing depends on weapon level", function()
    local p = Pattern.parse("X.x.o...")
    t.eq((Pattern.fires(p, 0, 1)), true)
    t.eq((Pattern.fires(p, 2, 1)), false)
    t.eq((Pattern.fires(p, 2, 3)), true)
    t.eq((Pattern.fires(p, 4, 4)), false)
    t.eq((Pattern.fires(p, 4, 5)), true)
    t.eq((Pattern.fires(p, 1, 99)), false)
  end)
  t.test("pattern wraps for absolute steps", function()
    local p = Pattern.parse("X...")
    t.eq((Pattern.fires(p, 4, 1)), true)
    t.eq((Pattern.fires(p, 1001, 1)), false)
    t.eq((Pattern.fires(p, 1000, 1)), true)
  end)
  t.test("velocity follows accent", function()
    local p = Pattern.parse("Xxo.")
    local _, v1 = Pattern.fires(p, 0, 9)
    local _, v3 = Pattern.fires(p, 2, 9)
    t.truthy(v1 > v3)
  end)
  t.test("density counts hits per loop", function()
    local p = Pattern.parse("X.x.o.X.")
    t.eq(Pattern.density(p, 1), 2)
    t.eq(Pattern.density(p, 3), 3)
    t.eq(Pattern.density(p, 5), 4)
  end)
end
